### ISSUE TITLE
Bogus gray status bar added to app window and cannot be removed

### ISSUE THREAD

**Issue by romanr** [bdbergeron/BDBSplitViewController#13]
There's a Gray status bar appears under the Master and detail controller. It can be seen through 1px gap between Master and Detail navigation bars.
And if you use Master without NavBar, it is completely exposed.
I spend hours trying different ways to remove that status bar or make it transparent, nothing works.

To reproduce:

In Master View Controller:

```
- (void)viewDidLoad
{
//.....
    self.navigationController.navigationBarHidden=YES;
    self.view.backgroundColor=[UIColor clearColor];

//
```

![image](https://cloud.githubusercontent.com/assets/329079/3847775/03242e38-1e69-11e4-95d8-6a37213af794.png)

**Comment by romanr** [comment]
After much investigation I was able to determine that this is a bug in Apple's implementation of UISplitViewController!
For no reason it adds this gray view above UISplitControlelr's background and below any nested subController views.
Submitted as rdar://17965956

It can be reproduced by creating Xcode New Project using "Master-Detail" Template, and then hiding the Master's Navigation Bar in code.

Apologies for posting this bug here.

The only way to make it work properly is to detect and hide that view after UISplitViewController displayed all views:

``` objc
@interface SplitVC : UISplitViewController
@end
@implementation
-(void)viewDidAppear:(BOOL)animated{
    [super viewDidAppear:animated];
    for (UIView *subview in [self.view subviews]) {
        if (subview.frame.size.height==20 && subview.frame.origin.y==0 && subview.frame.origin.x==0) {
            subview.hidden=YES;
        }
    }
}
@end
```

BDBSplitViewController is about the only known library that subclasses UISplitViewController.
Maybe you would want to add this workaround code in BDBSplitViewController's viewDidLoad?

**Comment by bdbergeron** [comment]
Thanks for investigating this, Roman. I will be doing a bit of my own later this evening or this weekend. Interesting that you basically have to hack the view hierarchy in order to hide that. Maybe there's a more elegant way, but without playing around with the issue myself, I can't say anything further.

**Comment by romanr** [comment]
Here's Screenshot from RevealApp showing that bogus view in hierarchy...
It actually stays 768px wide when device is in Landscape mode! Looks like UISplitViewController is supposed to hide it but forgets to do it.

![image](https://cloud.githubusercontent.com/assets/329079/3864251/5b5fcafa-1f57-11e4-8a3e-06df6506c626.png)

**Comment by bdbergeron** [comment]
After doing a bit of playing around, I found a super simple solution to this: don't use a UINavigationController as the master view controller. There's one catch, though; I wrote BDBSplitViewController to automatically wrap UIViewControllers in a nav controller because it seems to be the case that the vast majority of apps using a UISplitViewController have both the master and detail views embedded in nav controllers. However, you seem to want something a bit different, and I made an assumption that isn't true with a regular UIViewController, so I'm going to remove the auto-wrapping feature for the next release.

If you need the features provided with having a nav controller as the master view controller, you may just have to live with this issue until Apple corrects it, or use that snippet of code you have above.
